require('./factory')
require('./firebaseInit')
require('./auth')
require('./food')
require('./view')
require('./getData')
require('./setData')

require('./foodtest')
// require('./test')
// require('./test2')